moex_tickers = {"SBER", "GAZP", "GMKN", "LKOH", "ROSN", "YNDX", "NVTK", "ALRS", "AFKS", "TATN", "POLY", "SBERP", "NLMK",
                "PLZL", "TCSG", "VTBR", "MAGN", "MGNT", "AFLT", "CHMF", "HYDR", "RUAL", "IRAO", "MAIL", "MOEX", "SNGS",
                "MTSS", "SNGSP", "FIVE", "TATNP", "SIBN", "RSTI", "DSKY", "MTLR", "FEES", "OZON", "POGR", "TRNFP",
                "RTKM", "QIWI", "CBOM", "UPRO", "PHOR", "LNTA", "OGKB", "RASP", "FLOT", "AGRO", "MVID", "LSRG", "ENRU",
                "RNFT", "BANEP", "GLTR", "TGKA", "RGSS", "MTLRP", "NMTP", "MRKP", "RTKMP", "LSNGP", "PIKK", "TGKB",
                "NKHP", "GAZAP", "ETLN", "BSPB", "UWGN", "MRKC", "TRMK", "GAZA", "MSNG", "RSTIP", "BANE", "ENPG",
                "KZOSP", "INGR", "OKEY", "CHEP", "NKNCP", "VSMO", "PRFN", "AQUA", "ROLO", "LIFE", "MGTSP", "NKNC",
                "AKRN", "FESH", "PMSBP", "SELGP", "HHRU", "KRKNP", "TANL", "OBUV", "SELG", "MSST", "UNAC", "GCHE",
                "TTLK", "BISVP", "ISKJ", "IRKT", "LSNG", "GEMA", "SMLT", "RBCM", "KMAZ", "TGKN", "MDMG", "KOGK", "KZOS",
                "CNTLP", "MRKV", "LNZL", "MSTT", "BLNG", "YRSBP", "PAZA", "UNKL", "CHKZ", "MSRS", "BELU", "AMEZ",
                "RKKE", "VLHZ", "KLSB", "LNZLP", "TGKBP", "URKZ", "SVAV", "TGKD", "YRSB", "GTRK", "APTK", "MRKK",
                "ELTZ", "MRKZ", "USBN", "GRNT", "ZILL", "CNTL", "PMSB", "TUCH", "SLEN", "NNSBP", "CHMK", "SFIN",
                "MAGEP", "SIBG", "ALNU", "MGTS", "HIMCP", "VJGZ", "ABRD", "ZVEZ", "MRKU", "VGSB", "JNOS", "DASB",
                "RUGR", "RZSB", "KRKN", "DVEC", "KBTK", "MGNZ", "NFAZ", "IRGZ", "MAGE", "MRKS", "UTAR", "RUSP", "ACKO",
                "AVAN", "RTGZ", "ALBK", "KGKC", "MRSB", "NKSH", "KAZT", "NSVZ", "RLMN", "TGKDP", "TORSP", "VRSB",
                "YAKG", "VGSBP", "DIOD", "TUZA", "YKEN", "MRKY", "IGST", "KUBE", "KUZB", "GTLC", "NAUK", "STSBP",
                "MERF", "KAZTP", "VJGZP", "KROT", "KRSB", "RUSI", "IGSTP", "KCHE", "SAGOP", "EELT", "CHGZ", "MFGS",
                "TORS", "KCHEP", "KRSBP", "BRZL", "SARE", "ODVA", "SAGO", "RLMNP", "MFGSP", "LPSB", "ARSA", "ASSB",
                "KBSB", "TASBP", "YKENP", "UKUZ", "RDRB", "RTSB", "TASB", "ROSB", "VRSBP", "KMEZ", "RTSBP", "IDVP",
                "KRKOP", "VZRZP", "TNSE", "MISBP", "PRMB", "LVHK", "WTCM", "KGKCP", "SAREP", "NNSB", "HALS", "ROST",
                "MISB", "VSYD", "UCSS", "VSYDP", "WTCMP", "STSB", "KROTP", "KTSB", "DZRD", "KTSBP", "OMZZP", "RAVN",
                "DZRDP", "JNOSP", "KRKO", "GTSS", "TRFM", "GAZT", "DERZP", "VZRZ", "NPOF", "KMTZ", "MOBB", "GAZS",
                "URKA", "BISV", "MORI", "HIMC", "MFON", "KZMS", "GAZC", "TRCN", "KUNF", "TANLP", "KSGR"}